package View;


import Controller.GeriTeslimIslemleri;
import Controller.Odunc;
import Controller.EkranIslemContext;
import Controller.PersonelEkranOrtakIslemler;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author pelinustunel
 */
public class GeriTeslimEkrani extends javax.swing.JDialog implements PersonelEkranOrtakIslemler{

    DefaultTableModel model;
    GeriTeslimIslemleri teslimislemler = new GeriTeslimIslemleri();
    /**
     * Creates new form GeriTeslimEkrani
     */
    public GeriTeslimEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) odunc_tablosu.getModel();
        oduncGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        odunc_tablosu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        kitap_adi_alani = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kisi_adi_alani = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alinan_tarih_alani = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        teslim_tarihi_alani = new javax.swing.JTextField();
        teslimEt = new javax.swing.JButton();
        mesaj_yazisi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        odunc_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "book_id", "user_id", "loan_date", "return_date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        odunc_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                odunc_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(odunc_tablosu);
        if (odunc_tablosu.getColumnModel().getColumnCount() > 0) {
            odunc_tablosu.getColumnModel().getColumn(0).setResizable(false);
            odunc_tablosu.getColumnModel().getColumn(1).setResizable(false);
            odunc_tablosu.getColumnModel().getColumn(2).setResizable(false);
            odunc_tablosu.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("Kitap Adı:");

        jLabel2.setText("Kişi Adı");

        jLabel3.setText("Alınan Tarih:");

        jLabel4.setText("Teslim Tarihi:");

        teslimEt.setText("Teslim Et");
        teslimEt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teslimEtActionPerformed(evt);
            }
        });

        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 51));

        jButton1.setText("Geri Dön");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kitap_adi_alani)
                            .addComponent(kisi_adi_alani)
                            .addComponent(alinan_tarih_alani)
                            .addComponent(teslim_tarihi_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(teslimEt))))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(kitap_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kisi_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(alinan_tarih_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teslim_tarihi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(teslimEt)
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mesaj_yazisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void odunc_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odunc_tablosuMouseClicked
        int selectedrow = odunc_tablosu.getSelectedRow();
        kitap_adi_alani.setText(model.getValueAt(selectedrow, 0).toString()); // book_id
    kisi_adi_alani.setText(model.getValueAt(selectedrow, 1).toString()); // user_id
    alinan_tarih_alani.setText(model.getValueAt(selectedrow, 2).toString()); // loan_date
    teslim_tarihi_alani.setText(model.getValueAt(selectedrow, 3).toString()); // return_date

        
    }//GEN-LAST:event_odunc_tablosuMouseClicked

    private void teslimEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teslimEtActionPerformed
       mesaj_yazisi.setText("");

    int selectedrow = odunc_tablosu.getSelectedRow();

    if (selectedrow == -1) {
        if (model.getRowCount() == 0) {
            mesaj_yazisi.setText("Kitap Tablosu şu anda boş");
        } else {
            mesaj_yazisi.setText("Lütfen silmek istediğiniz kitabı seçiniz...");
        }
    } else {
        int book_id = (int) model.getValueAt(selectedrow, 0);

        teslimislemler.oduncTeslimEt(book_id);
        oduncGoruntule();
        mesaj_yazisi.setText("Teslim işlemi başarıyla gerçekleştirildi.");
    }
    }//GEN-LAST:event_teslimEtActionPerformed

    public void geriDonEkran(){
        PersonelAraEkran araEkran = new PersonelAraEkran();
        setVisible(false);
        araEkran.setVisible(true);
    }
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        geriDonEkran();
    }//GEN-LAST:event_jButton1MouseClicked

     // Odunc tablosunun Görüntülenmesi
    public void oduncGoruntule(){
        
        model.setRowCount(0);
        ArrayList<Odunc> oduncler = new ArrayList<Odunc>();
        
        EkranIslemContext oduncleriGetir = new EkranIslemContext(teslimislemler);
        oduncler = oduncleriGetir.calistirStrategy();
        
        
        if(oduncler != null) {
            
            for(Odunc odunc : oduncler) {
                Object[] eklenecek = {odunc.getBook_id(),odunc.getUser_id(),odunc.getLoan_date(),odunc.getReturn_date()};
                model.addRow(eklenecek);
            }
            
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeriTeslimEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeriTeslimEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeriTeslimEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeriTeslimEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GeriTeslimEkrani dialog = new GeriTeslimEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alinan_tarih_alani;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kisi_adi_alani;
    private javax.swing.JTextField kitap_adi_alani;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTable odunc_tablosu;
    private javax.swing.JButton teslimEt;
    private javax.swing.JTextField teslim_tarihi_alani;
    // End of variables declaration//GEN-END:variables
}
