package View;


import Controller.Uyeler;
import Controller.KullaniciIslemleri;
import Controller.EkranIslemContext;
import Controller.PersonelEkranOrtakIslemler;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author pelinustunel
 */
public class KullaniciEkrani extends javax.swing.JDialog implements PersonelEkranOrtakIslemler{

    DefaultTableModel model;
    KullaniciIslemleri islemler = new KullaniciIslemleri();
    
    
    public KullaniciEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) kullanici_tablosu.getModel();
        uyeleriGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arama_cubugu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ad_alani = new javax.swing.JTextField();
        parola_alani = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefon_alani = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        kullanici_tablosu = new javax.swing.JTable();
        kullaniciGuncelle = new javax.swing.JButton();
        kullaniciSil = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        email_alani = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        geriDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kullanıcı Adı:");

        jLabel2.setText("Parola:");

        jLabel3.setText("Telefon");

        kullanici_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "user_id", "username", "password", "user_type", "telefon", "email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kullanici_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kullanici_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kullanici_tablosu);
        if (kullanici_tablosu.getColumnModel().getColumnCount() > 0) {
            kullanici_tablosu.getColumnModel().getColumn(0).setResizable(false);
            kullanici_tablosu.getColumnModel().getColumn(1).setResizable(false);
            kullanici_tablosu.getColumnModel().getColumn(3).setResizable(false);
            kullanici_tablosu.getColumnModel().getColumn(4).setResizable(false);
            kullanici_tablosu.getColumnModel().getColumn(5).setResizable(false);
        }

        kullaniciGuncelle.setText("Kullanıcı Güncelle");
        kullaniciGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciGuncelleActionPerformed(evt);
            }
        });

        kullaniciSil.setText("Kullanıcı Sil");
        kullaniciSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciSilActionPerformed(evt);
            }
        });

        jLabel4.setText("Email:");

        mesaj_yazisi.setForeground(new java.awt.Color(255, 51, 51));

        geriDon.setText("Geri Dön");
        geriDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriDonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(parola_alani)
                                    .addComponent(ad_alani)
                                    .addComponent(telefon_alani)
                                    .addComponent(email_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(kullaniciGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(kullaniciSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(geriDon))))
                        .addGap(0, 89, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullaniciGuncelle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(parola_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullaniciSil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telefon_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geriDon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullaniciGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciGuncelleActionPerformed
        
        String username = ad_alani.getText();
        String password = parola_alani.getText();
        String telefon = telefon_alani.getText();
        String email = email_alani.getText();
        
        int selectedrow = kullanici_tablosu.getSelectedRow();
        
        if (selectedrow == -1) {
            
            if(model.getRowCount() == 0) {
                
                mesaj_yazisi.setText("Kullanıcı Tablosu şu anda boş");     
            } else {
                
                 mesaj_yazisi.setText("Güncellemek istediğiniz üyeyi seçmediğiniz için işlem yapılamamaktadır"); 
            }  
        } else {
            
            int user_id = (int) model.getValueAt(selectedrow, 0);
            
            islemler.uyeGuncelle(user_id,username,password,telefon,email);
            uyeleriGoruntule();
            mesaj_yazisi.setText("Üye başarıyla güncellendi.");
        }
    }//GEN-LAST:event_kullaniciGuncelleActionPerformed

    private void kullanici_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici_tablosuMouseClicked
        
        int selectedrow = kullanici_tablosu.getSelectedRow();
        ad_alani .setText(model.getValueAt(selectedrow,1).toString());
        parola_alani .setText(model.getValueAt(selectedrow,2).toString());
        telefon_alani .setText(model.getValueAt(selectedrow,4).toString());
        email_alani .setText(model.getValueAt(selectedrow,5).toString());
    }//GEN-LAST:event_kullanici_tablosuMouseClicked

    private void kullaniciSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciSilActionPerformed
         mesaj_yazisi.setText("");
        
        int selectedrow = kullanici_tablosu.getSelectedRow();
        
        if (selectedrow == -1){
            
            if (model.getRowCount() == 0){
                
                mesaj_yazisi.setText("Kullanıcı Tablosu şu anda boş");   
            } else {
                mesaj_yazisi.setText("Lütfen silmek istediğiniz kitabı seçiniz..."); 
            } 
        } else {
            
            int book_id = (int) model.getValueAt(selectedrow,0);
            
            islemler.uyeSil(book_id);
            uyeleriGoruntule();
            mesaj_yazisi.setText("Üye başarıyla silindi.");
            
        } 
    }//GEN-LAST:event_kullaniciSilActionPerformed

    public void geriDonEkran(){
        PersonelAraEkran araEkran = new PersonelAraEkran();
        setVisible(false);
        araEkran.setVisible(true);
    }
    
    private void geriDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriDonMouseClicked
        geriDonEkran();
    }//GEN-LAST:event_geriDonMouseClicked

     // Kitap tablosunun Görüntülenmesi
    public void uyeleriGoruntule(){
        
        model.setRowCount(0);
        ArrayList<Uyeler> uye = new ArrayList<Uyeler>();
        
        
        EkranIslemContext uyeleriGetir = new EkranIslemContext(islemler);
        uye = uyeleriGetir.calistirStrategy();
        
        if(uye != null) {
            
            for(Uyeler uyeler : uye) {
                Object[] eklenecek = {uyeler.getUser_id(),uyeler.getUsername(),uyeler.getPassword(),uyeler.getUserType(),uyeler.getTelefon(),uyeler.getEmail()};
                model.addRow(eklenecek);
            }
            
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KullaniciEkrani dialog = new KullaniciEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alani;
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JTextField email_alani;
    private javax.swing.JButton geriDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kullaniciGuncelle;
    private javax.swing.JButton kullaniciSil;
    private javax.swing.JTable kullanici_tablosu;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTextField parola_alani;
    private javax.swing.JTextField telefon_alani;
    // End of variables declaration//GEN-END:variables
}
