package View;


import Controller.PersonelAraEkranFacade;
import Controller.KullaniciIslemleri;
import View.OduncAlmaEkrani;
import View.KullaniciEkrani;
import View.KitapEkrani;
import View.GirisYapEkrani;
import View.GeriTeslimEkrani;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pelinustunel
 */
public class PersonelAraEkran extends javax.swing.JFrame {

    private final PersonelAraEkranFacade facade; // Create an instance of the Facade
    
    public PersonelAraEkran() {
        initComponents();
        facade = new PersonelAraEkranFacade(); // Initialize the Facade in the constructor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kitap_islem = new javax.swing.JButton();
        kullanici_islem = new javax.swing.JButton();
        geriDon = new javax.swing.JButton();
        odunc_Clicked = new javax.swing.JButton();
        teslimAl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kitap_islem.setText("Kitap İşlemleri");
        kitap_islem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitap_islemMouseClicked(evt);
            }
        });

        kullanici_islem.setText("Kullanıcı İşlemleri");
        kullanici_islem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kullanici_islemMouseClicked(evt);
            }
        });

        geriDon.setText("Geri Dön");
        geriDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriDonMouseClicked(evt);
            }
        });

        odunc_Clicked.setText("Ödünç Ver");
        odunc_Clicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                odunc_ClickedMouseClicked(evt);
            }
        });

        teslimAl.setText("Teslim Al");
        teslimAl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teslimAlMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(geriDon)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(kitap_islem)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teslimAl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kullanici_islem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54))))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(odunc_Clicked, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitap_islem)
                    .addComponent(kullanici_islem))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odunc_Clicked)
                    .addComponent(teslimAl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(geriDon)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kitap_islemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitap_islemMouseClicked
           KitapEkrani kitapEkrani = facade.getKitapEkran(); // Access KitapEkrani through the Facade
            setVisible(false);
            kitapEkrani.setVisible(true);
    }//GEN-LAST:event_kitap_islemMouseClicked

    private void kullanici_islemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici_islemMouseClicked
           KullaniciEkrani kullaniciEkrani = facade.getKullaniciEkran(); // Access KullaniciEkrani through the Facade
            setVisible(false);
            kullaniciEkrani.setVisible(true);
    }//GEN-LAST:event_kullanici_islemMouseClicked

    private void geriDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriDonMouseClicked
        GirisYapEkrani giris = new GirisYapEkrani();
        setVisible(false);
        giris.setVisible(true);
    }//GEN-LAST:event_geriDonMouseClicked

    private void odunc_ClickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odunc_ClickedMouseClicked
        OduncAlmaEkrani odunc = facade.getOduncEkran(); // Access OduncAlmaEkrani through the Facade
        setVisible(false);
        odunc.setVisible(true);
    }//GEN-LAST:event_odunc_ClickedMouseClicked

    private void teslimAlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teslimAlMouseClicked
        GeriTeslimEkrani geriTeslim = facade.getTeslimEkran(); // Access GeriTeslimEkrani through the Facade
        setVisible(false);
        geriTeslim.setVisible(true);
    }//GEN-LAST:event_teslimAlMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelAraEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelAraEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelAraEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelAraEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelAraEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton geriDon;
    private javax.swing.JButton kitap_islem;
    private javax.swing.JButton kullanici_islem;
    private javax.swing.JButton odunc_Clicked;
    private javax.swing.JButton teslimAl;
    // End of variables declaration//GEN-END:variables
}
